In [5]:
np.random.seed(42)
samples = np.random.exponential(4, size= 10000)
print(samples[:5])

[ 1.87707236 12.04048572  5.26698277  3.65177022  0.67849948]


In [2]:
import numpy as np

##### Pick 
the 
option 
below 
that 
correctly 
describe 
the 
difference 
between 
an 
Empirical 
Cumulative 
Distribution 
Function 
(ECDF) 
and 
a 
Cumulative 
Distribution 
Function 
(CDF). 

In [8]:
np.random.seed(42)
samples = np.random.normal( 7, 0.5, size= 10000)
print(samples[:5])

[7.24835708 6.93086785 7.32384427 7.76151493 6.88292331]


In [9]:
np.random.seed(42)
output = np.random.poisson(2,size =10000)
print(output[:10])

[4 1 3 3 1 2 1 1 2 2]


In [10]:
n = len(data)
x = np.sort(data)
y = np.arange(1, n+1) / n
print(data.head())

NameError: name 'data' is not defined